// Code generated by go generate; DO NOT EDIT.
// This file was generated at 2018 Aug 08 11:02:02 UTC

// Copyright 2018 Dennis Kuhnert
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Package flt64slice provides ...
package flt64slice

// floats64 ...
type floats64 []float64

// Map ...
func Map(s []float64, f func(s float64) float64) floats64 {
	m := floats64(make([]float64, len(s)))
	for i, v := range s {
		m[i] = f(v)
	}
	return m
}

// Map ...
func (s floats64) Map(f func(s float64) float64) floats64 {
	return Map(s, f)
}

// Filter ...
func Filter(s []float64, f func(s float64) bool) floats64 {
	m := floats64(make([]float64, 0, len(s)))
	for _, v := range s {
		if f(v) {
			m = append(m, v)
		}
	}
	return m
}

// Filter ...
func (s floats64) Filter(f func(s float64) bool) floats64 {
	return Filter(s, f)
}

// Reduce ...
func Reduce(s []float64, f func(sum, value float64) float64, neutral float64) float64 {
	res := neutral
	for _, e := range s {
		res = f(res, e)
	}
	return res
}

// Reduce ...
func (s floats64) Reduce(f func(sum, value float64) float64, neutral float64) float64 {
	return Reduce(s, f, neutral)
}

// Unique ...
func Unique(s []float64) floats64 {
	m := floats64(make([]float64, 0, len(s)))
	seen := make(map[float64]struct{})
	for _, v := range s {
		if _, ok := seen[v]; !ok {
			m = append(m, v)
			seen[v] = struct{}{}
		}
	}
	return m
}

// Unique ...
func (s floats64) Unique() floats64 {
	return Unique(s)
}
