// Code generated by go generate; DO NOT EDIT.

// Copyright 2018 Dennis Kuhnert
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package convert

import (
	"github.com/kyroy/go-slices/bools"
	"github.com/kyroy/go-slices/float32s"
	"github.com/kyroy/go-slices/float64s"
	"github.com/kyroy/go-slices/interfaces"
	"github.com/kyroy/go-slices/int8s"
	"github.com/kyroy/go-slices/int16s"
	"github.com/kyroy/go-slices/int32s"
	"github.com/kyroy/go-slices/int64s"
	"github.com/kyroy/go-slices/uint8s"
	"github.com/kyroy/go-slices/uint16s"
	"github.com/kyroy/go-slices/uint32s"
	"github.com/kyroy/go-slices/uint64s"
	"github.com/kyroy/go-slices/ints"
	"github.com/kyroy/go-slices/uints"
	"github.com/kyroy/go-slices/bytes"
	"github.com/kyroy/go-slices/runes"
	"github.com/kyroy/go-slices/complex64s"
	"github.com/kyroy/go-slices/uintptrs"
	"github.com/kyroy/go-slices/strings"
)

// Complex128sBools creates a new slice with the results of calling the provided function on every element in the given array.
func Complex128sBools(s []complex128, f func(s complex128) bool) bools.Bools {
	m := bools.Bools(make([]bool, len(s)))
	for i, v := range s {
		m[i] = f(v)
	}
	return m
}

// Complex128sFloat32s creates a new slice with the results of calling the provided function on every element in the given array.
func Complex128sFloat32s(s []complex128, f func(s complex128) float32) float32s.Float32s {
	m := float32s.Float32s(make([]float32, len(s)))
	for i, v := range s {
		m[i] = f(v)
	}
	return m
}

// Complex128sFloat64s creates a new slice with the results of calling the provided function on every element in the given array.
func Complex128sFloat64s(s []complex128, f func(s complex128) float64) float64s.Float64s {
	m := float64s.Float64s(make([]float64, len(s)))
	for i, v := range s {
		m[i] = f(v)
	}
	return m
}

// Complex128sInterfaces creates a new slice with the results of calling the provided function on every element in the given array.
func Complex128sInterfaces(s []complex128, f func(s complex128) interface{}) interfaces.Interfaces {
	m := interfaces.Interfaces(make([]interface{}, len(s)))
	for i, v := range s {
		m[i] = f(v)
	}
	return m
}

// Complex128sInt8s creates a new slice with the results of calling the provided function on every element in the given array.
func Complex128sInt8s(s []complex128, f func(s complex128) int8) int8s.Int8s {
	m := int8s.Int8s(make([]int8, len(s)))
	for i, v := range s {
		m[i] = f(v)
	}
	return m
}

// Complex128sInt16s creates a new slice with the results of calling the provided function on every element in the given array.
func Complex128sInt16s(s []complex128, f func(s complex128) int16) int16s.Int16s {
	m := int16s.Int16s(make([]int16, len(s)))
	for i, v := range s {
		m[i] = f(v)
	}
	return m
}

// Complex128sInt32s creates a new slice with the results of calling the provided function on every element in the given array.
func Complex128sInt32s(s []complex128, f func(s complex128) int32) int32s.Int32s {
	m := int32s.Int32s(make([]int32, len(s)))
	for i, v := range s {
		m[i] = f(v)
	}
	return m
}

// Complex128sInt64s creates a new slice with the results of calling the provided function on every element in the given array.
func Complex128sInt64s(s []complex128, f func(s complex128) int64) int64s.Int64s {
	m := int64s.Int64s(make([]int64, len(s)))
	for i, v := range s {
		m[i] = f(v)
	}
	return m
}

// Complex128sUint8s creates a new slice with the results of calling the provided function on every element in the given array.
func Complex128sUint8s(s []complex128, f func(s complex128) uint8) uint8s.Uint8s {
	m := uint8s.Uint8s(make([]uint8, len(s)))
	for i, v := range s {
		m[i] = f(v)
	}
	return m
}

// Complex128sUint16s creates a new slice with the results of calling the provided function on every element in the given array.
func Complex128sUint16s(s []complex128, f func(s complex128) uint16) uint16s.Uint16s {
	m := uint16s.Uint16s(make([]uint16, len(s)))
	for i, v := range s {
		m[i] = f(v)
	}
	return m
}

// Complex128sUint32s creates a new slice with the results of calling the provided function on every element in the given array.
func Complex128sUint32s(s []complex128, f func(s complex128) uint32) uint32s.Uint32s {
	m := uint32s.Uint32s(make([]uint32, len(s)))
	for i, v := range s {
		m[i] = f(v)
	}
	return m
}

// Complex128sUint64s creates a new slice with the results of calling the provided function on every element in the given array.
func Complex128sUint64s(s []complex128, f func(s complex128) uint64) uint64s.Uint64s {
	m := uint64s.Uint64s(make([]uint64, len(s)))
	for i, v := range s {
		m[i] = f(v)
	}
	return m
}

// Complex128sInts creates a new slice with the results of calling the provided function on every element in the given array.
func Complex128sInts(s []complex128, f func(s complex128) int) ints.Ints {
	m := ints.Ints(make([]int, len(s)))
	for i, v := range s {
		m[i] = f(v)
	}
	return m
}

// Complex128sUints creates a new slice with the results of calling the provided function on every element in the given array.
func Complex128sUints(s []complex128, f func(s complex128) uint) uints.Uints {
	m := uints.Uints(make([]uint, len(s)))
	for i, v := range s {
		m[i] = f(v)
	}
	return m
}

// Complex128sBytes creates a new slice with the results of calling the provided function on every element in the given array.
func Complex128sBytes(s []complex128, f func(s complex128) byte) bytes.Bytes {
	m := bytes.Bytes(make([]byte, len(s)))
	for i, v := range s {
		m[i] = f(v)
	}
	return m
}

// Complex128sRunes creates a new slice with the results of calling the provided function on every element in the given array.
func Complex128sRunes(s []complex128, f func(s complex128) rune) runes.Runes {
	m := runes.Runes(make([]rune, len(s)))
	for i, v := range s {
		m[i] = f(v)
	}
	return m
}

// Complex128sComplex64s creates a new slice with the results of calling the provided function on every element in the given array.
func Complex128sComplex64s(s []complex128, f func(s complex128) complex64) complex64s.Complex64s {
	m := complex64s.Complex64s(make([]complex64, len(s)))
	for i, v := range s {
		m[i] = f(v)
	}
	return m
}

// Complex128sUintptrs creates a new slice with the results of calling the provided function on every element in the given array.
func Complex128sUintptrs(s []complex128, f func(s complex128) uintptr) uintptrs.Uintptrs {
	m := uintptrs.Uintptrs(make([]uintptr, len(s)))
	for i, v := range s {
		m[i] = f(v)
	}
	return m
}

// Complex128sStrings creates a new slice with the results of calling the provided function on every element in the given array.
func Complex128sStrings(s []complex128, f func(s complex128) string) strings.Strings {
	m := strings.Strings(make([]string, len(s)))
	for i, v := range s {
		m[i] = f(v)
	}
	return m
}
