// Code generated by go generate; DO NOT EDIT.

// Copyright 2018 Dennis Kuhnert
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package convert

import (
	"github.com/kyroy/go-slices/bools"
	"github.com/kyroy/go-slices/float32s"
	"github.com/kyroy/go-slices/float64s"
	"github.com/kyroy/go-slices/interfaces"
	"github.com/kyroy/go-slices/int8s"
	"github.com/kyroy/go-slices/int16s"
	"github.com/kyroy/go-slices/int32s"
	"github.com/kyroy/go-slices/int64s"
	"github.com/kyroy/go-slices/uint8s"
	"github.com/kyroy/go-slices/uint16s"
	"github.com/kyroy/go-slices/uint32s"
	"github.com/kyroy/go-slices/uint64s"
	"github.com/kyroy/go-slices/ints"
	"github.com/kyroy/go-slices/uints"
	"github.com/kyroy/go-slices/bytes"
	"github.com/kyroy/go-slices/runes"
	"github.com/kyroy/go-slices/complex128s"
	"github.com/kyroy/go-slices/uintptrs"
	"github.com/kyroy/go-slices/strings"
)

// Complex64sBools creates a new slice with the results of calling the provided function on every element in the given array.
func Complex64sBools(s []complex64, f func(s complex64) bool) bools.Bools {
	m := bools.Bools(make([]bool, len(s)))
	for i, v := range s {
		m[i] = f(v)
	}
	return m
}

// Complex64sFloat32s creates a new slice with the results of calling the provided function on every element in the given array.
func Complex64sFloat32s(s []complex64, f func(s complex64) float32) float32s.Float32s {
	m := float32s.Float32s(make([]float32, len(s)))
	for i, v := range s {
		m[i] = f(v)
	}
	return m
}

// Complex64sFloat64s creates a new slice with the results of calling the provided function on every element in the given array.
func Complex64sFloat64s(s []complex64, f func(s complex64) float64) float64s.Float64s {
	m := float64s.Float64s(make([]float64, len(s)))
	for i, v := range s {
		m[i] = f(v)
	}
	return m
}

// Complex64sInterfaces creates a new slice with the results of calling the provided function on every element in the given array.
func Complex64sInterfaces(s []complex64, f func(s complex64) interface{}) interfaces.Interfaces {
	m := interfaces.Interfaces(make([]interface{}, len(s)))
	for i, v := range s {
		m[i] = f(v)
	}
	return m
}

// Complex64sInt8s creates a new slice with the results of calling the provided function on every element in the given array.
func Complex64sInt8s(s []complex64, f func(s complex64) int8) int8s.Int8s {
	m := int8s.Int8s(make([]int8, len(s)))
	for i, v := range s {
		m[i] = f(v)
	}
	return m
}

// Complex64sInt16s creates a new slice with the results of calling the provided function on every element in the given array.
func Complex64sInt16s(s []complex64, f func(s complex64) int16) int16s.Int16s {
	m := int16s.Int16s(make([]int16, len(s)))
	for i, v := range s {
		m[i] = f(v)
	}
	return m
}

// Complex64sInt32s creates a new slice with the results of calling the provided function on every element in the given array.
func Complex64sInt32s(s []complex64, f func(s complex64) int32) int32s.Int32s {
	m := int32s.Int32s(make([]int32, len(s)))
	for i, v := range s {
		m[i] = f(v)
	}
	return m
}

// Complex64sInt64s creates a new slice with the results of calling the provided function on every element in the given array.
func Complex64sInt64s(s []complex64, f func(s complex64) int64) int64s.Int64s {
	m := int64s.Int64s(make([]int64, len(s)))
	for i, v := range s {
		m[i] = f(v)
	}
	return m
}

// Complex64sUint8s creates a new slice with the results of calling the provided function on every element in the given array.
func Complex64sUint8s(s []complex64, f func(s complex64) uint8) uint8s.Uint8s {
	m := uint8s.Uint8s(make([]uint8, len(s)))
	for i, v := range s {
		m[i] = f(v)
	}
	return m
}

// Complex64sUint16s creates a new slice with the results of calling the provided function on every element in the given array.
func Complex64sUint16s(s []complex64, f func(s complex64) uint16) uint16s.Uint16s {
	m := uint16s.Uint16s(make([]uint16, len(s)))
	for i, v := range s {
		m[i] = f(v)
	}
	return m
}

// Complex64sUint32s creates a new slice with the results of calling the provided function on every element in the given array.
func Complex64sUint32s(s []complex64, f func(s complex64) uint32) uint32s.Uint32s {
	m := uint32s.Uint32s(make([]uint32, len(s)))
	for i, v := range s {
		m[i] = f(v)
	}
	return m
}

// Complex64sUint64s creates a new slice with the results of calling the provided function on every element in the given array.
func Complex64sUint64s(s []complex64, f func(s complex64) uint64) uint64s.Uint64s {
	m := uint64s.Uint64s(make([]uint64, len(s)))
	for i, v := range s {
		m[i] = f(v)
	}
	return m
}

// Complex64sInts creates a new slice with the results of calling the provided function on every element in the given array.
func Complex64sInts(s []complex64, f func(s complex64) int) ints.Ints {
	m := ints.Ints(make([]int, len(s)))
	for i, v := range s {
		m[i] = f(v)
	}
	return m
}

// Complex64sUints creates a new slice with the results of calling the provided function on every element in the given array.
func Complex64sUints(s []complex64, f func(s complex64) uint) uints.Uints {
	m := uints.Uints(make([]uint, len(s)))
	for i, v := range s {
		m[i] = f(v)
	}
	return m
}

// Complex64sBytes creates a new slice with the results of calling the provided function on every element in the given array.
func Complex64sBytes(s []complex64, f func(s complex64) byte) bytes.Bytes {
	m := bytes.Bytes(make([]byte, len(s)))
	for i, v := range s {
		m[i] = f(v)
	}
	return m
}

// Complex64sRunes creates a new slice with the results of calling the provided function on every element in the given array.
func Complex64sRunes(s []complex64, f func(s complex64) rune) runes.Runes {
	m := runes.Runes(make([]rune, len(s)))
	for i, v := range s {
		m[i] = f(v)
	}
	return m
}

// Complex64sComplex128s creates a new slice with the results of calling the provided function on every element in the given array.
func Complex64sComplex128s(s []complex64, f func(s complex64) complex128) complex128s.Complex128s {
	m := complex128s.Complex128s(make([]complex128, len(s)))
	for i, v := range s {
		m[i] = f(v)
	}
	return m
}

// Complex64sUintptrs creates a new slice with the results of calling the provided function on every element in the given array.
func Complex64sUintptrs(s []complex64, f func(s complex64) uintptr) uintptrs.Uintptrs {
	m := uintptrs.Uintptrs(make([]uintptr, len(s)))
	for i, v := range s {
		m[i] = f(v)
	}
	return m
}

// Complex64sStrings creates a new slice with the results of calling the provided function on every element in the given array.
func Complex64sStrings(s []complex64, f func(s complex64) string) strings.Strings {
	m := strings.Strings(make([]string, len(s)))
	for i, v := range s {
		m[i] = f(v)
	}
	return m
}
