// Code generated by go generate; DO NOT EDIT.

// Copyright 2018 Dennis Kuhnert
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package bools_test

import (
	"fmt"
	"github.com/kyroy/go-slices/bools"
	"github.com/stretchr/testify/assert"
	"testing"
)

var _ = fmt.Print

func TestMap(t *testing.T) {
	type args struct {
		s []bool
		f func(s bool) bool
	}
	tests := []struct {
		name string
		args args
		want []bool
	}{
		{
			name: "basic",
			args: args{
				s: []bool{true, false, true},
				f: func(x bool) bool { return !x },
			},
			want: []bool{false, true, false},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			var got []bool = bools.Map(tt.args.s, tt.args.f)
			assert.Equal(t, tt.want, got)
			got = bools.New(tt.args.s).Map(tt.args.f)
			assert.Equal(t, tt.want, got)
		})
	}
}

func TestFilter(t *testing.T) {
	type args struct {
		s []bool
		f func(s bool) bool
	}
	tests := []struct {
		name string
		args args
		want []bool
	}{
		{
			name: "basic",
			args: args{
				s: []bool{true, false, true},
				f: func(x bool) bool { return x },
			},
			want: []bool{true, true},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			var got []bool = bools.Filter(tt.args.s, tt.args.f)
			assert.Equal(t, tt.want, got)
			got = bools.New(tt.args.s).Filter(tt.args.f)
			assert.Equal(t, tt.want, got)
		})
	}
}

func TestReduce(t *testing.T) {
	type args struct {
		s       []bool
		f       func(sum, value bool) bool
		neutral bool
	}
	tests := []struct {
		name string
		args args
		want bool
	}{
		{
			name: "and_false",
			args: args{
				s:       []bool{true, false, true},
				f:       func(sum, value bool) bool { return sum && value },
				neutral: true,
			},
			want: false,
		}, {
			name: "and_true",
			args: args{
				s:       []bool{true, true, true},
				f:       func(sum, value bool) bool { return sum && value },
				neutral: true,
			},
			want: true,
		}, {
			name: "or_true",
			args: args{
				s:       []bool{false, false, true},
				f:       func(sum, value bool) bool { return sum || value },
				neutral: false,
			},
			want: true,
		}, {
			name: "or_false",
			args: args{
				s:       []bool{false, false, false},
				f:       func(sum, value bool) bool { return sum || value },
				neutral: false,
			},
			want: false,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			var got bool = bools.Reduce(tt.args.s, tt.args.f, tt.args.neutral)
			assert.Equal(t, tt.want, got)
			got = bools.New(tt.args.s).Reduce(tt.args.f, tt.args.neutral)
			assert.Equal(t, tt.want, got)
		})
	}
}

func TestUnique(t *testing.T) {
	type args struct {
		s []bool
	}
	tests := []struct {
		name string
		args args
		want []bool
	}{
		{
			name: "basic",
			args: args{
				s: []bool{false, false, true, true},
			},
			want: []bool{false, true},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			var got []bool = bools.Unique(tt.args.s)
			assert.Equal(t, tt.want, got)
			got = bools.New(tt.args.s).Unique()
			assert.Equal(t, tt.want, got)
		})
	}
}

func TestIntersect(t *testing.T) {
	type args struct {
		s    []bool
		more [][]bool
	}
	tests := []struct {
		name string
		args args
		want []bool
	}{
		{
			name: "same",
			args: args{
				s:    []bool{false, true, false},
				more: [][]bool{{false, true, false}},
			},
			want: []bool{false, true, false},
		}, {
			name: "multiple",
			args: args{
				s:    []bool{false, true, false, true},
				more: [][]bool{{false, true, false, false}, {false, true, false, true, false}},
			},
			want: []bool{false, true, false},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			var got []bool = bools.Intersect(tt.args.s, tt.args.more...)
			assert.ElementsMatch(t, tt.want, got)
			got = bools.New(tt.args.s).Intersect(tt.args.more...)
			assert.ElementsMatch(t, tt.want, got)
		})
	}
}

func TestContains(t *testing.T) {
	type args struct {
		s []bool
		x bool
	}
	tests := []struct {
		name string
		args args
		want bool
	}{
		{
			name: "contains",
			args: args{
				s: []bool{true, false, true},
				x: false,
			},
			want: true,
		}, {
			name: "not_contains",
			args: args{
				s: []bool{true, true, true},
				x: false,
			},
			want: false,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			var got bool = bools.Contains(tt.args.s, tt.args.x)
			assert.Equal(t, tt.want, got)
			got = bools.New(tt.args.s).Contains(tt.args.x)
			assert.Equal(t, tt.want, got)
		})
	}
}

func TestIndexOf(t *testing.T) {
	type args struct {
		s []bool
		x bool
	}
	tests := []struct {
		name string
		args args
		want int
	}{
		{
			name: "contains",
			args: args{
				s: []bool{true, false, true},
				x: false,
			},
			want: 1,
		}, {
			name: "not_contains",
			args: args{
				s: []bool{true, true, true},
				x: false,
			},
			want: -1,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			var got int = bools.IndexOf(tt.args.s, tt.args.x)
			assert.Equal(t, tt.want, got)
			got = bools.New(tt.args.s).IndexOf(tt.args.x)
			assert.Equal(t, tt.want, got)
		})
	}
}

func TestFind(t *testing.T) {
	type args struct {
		s []bool
		f func(bool) bool
	}
	tests := []struct {
		name  string
		args  args
		want  bool
		found bool
	}{
		{
			name: "contains",
			args: args{
				s: []bool{true, false, true},
				f: func(x bool) bool { return x },
			},
			want:  true,
			found: true,
		}, {
			name: "not_contains",
			args: args{
				s: []bool{false, false, false},
				f: func(x bool) bool { return x },
			},
			want:  true,
			found: false,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			var got1 *bool = bools.Find(tt.args.s, tt.args.f)
			var got2 *bool = bools.New(tt.args.s).Find(tt.args.f)
			if tt.found {
				assert.Equal(t, &tt.want, got1)
				assert.Equal(t, &tt.want, got2)
			} else {
				assert.Nil(t, got1)
				assert.Nil(t, got2)
			}
		})
	}
}
