// Code generated by go generate; DO NOT EDIT.
// This file was generated at 2018 Aug 08 11:10:39 UTC

// Copyright 2018 Dennis Kuhnert
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Package bools provides ...
package bools

// bools ...
type bools []bool

// Map ...
func Map(s []bool, f func(s bool) bool) bools {
	m := bools(make([]bool, len(s)))
	for i, v := range s {
		m[i] = f(v)
	}
	return m
}

// Map ...
func (s bools) Map(f func(s bool) bool) bools {
	return Map(s, f)
}

// Filter ...
func Filter(s []bool, f func(s bool) bool) bools {
	m := bools(make([]bool, 0, len(s)))
	for _, v := range s {
		if f(v) {
			m = append(m, v)
		}
	}
	return m
}

// Filter ...
func (s bools) Filter(f func(s bool) bool) bools {
	return Filter(s, f)
}

// Reduce ...
func Reduce(s []bool, f func(sum, value bool) bool, neutral bool) bool {
	res := neutral
	for _, e := range s {
		res = f(res, e)
	}
	return res
}

// Reduce ...
func (s bools) Reduce(f func(sum, value bool) bool, neutral bool) bool {
	return Reduce(s, f, neutral)
}

// Unique ...
func Unique(s []bool) bools {
	m := bools(make([]bool, 0, len(s)))
	seen := make(map[bool]struct{})
	for _, v := range s {
		if _, ok := seen[v]; !ok {
			m = append(m, v)
			seen[v] = struct{}{}
		}
	}
	return m
}

// Unique ...
func (s bools) Unique() bools {
	return Unique(s)
}
