// Code generated by go generate; DO NOT EDIT.

// Copyright 2018 Dennis Kuhnert
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package interfaces_test

import (
	"fmt"
	"github.com/kyroy/go-slices/interfaces"
	"github.com/stretchr/testify/assert"
	"testing"
)

var _ = fmt.Print

func TestMap(t *testing.T) {
	type args struct {
		s []interface{}
		f func(s interface{}) interface{}
	}
	tests := []struct {
		name string
		args args
		want []interface{}
	}{
		{
			name: "basic",
			args: args{
				s: []interface{}{"a", 1, "1", 2},
				f: func(x interface{}) interface{} { switch a := x.(type) { case string: return a + "!"; case int: return a + 1; default: return a } },
			},
			want: []interface{}{"a!", 2, "1!", 3},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			var got []interface{} = interfaces.Map(tt.args.s, tt.args.f)
			assert.Equal(t, tt.want, got)
			got = interfaces.New(tt.args.s).Map(tt.args.f)
			assert.Equal(t, tt.want, got)
		})
	}
}

func TestFilter(t *testing.T) {
	type args struct {
		s []interface{}
		f func(s interface{}) bool
	}
	tests := []struct {
		name string
		args args
		want []interface{}
	}{
		{
			name: "basic",
			args: args{
				s: []interface{}{"a", 1, "1", 2},
				f: func(x interface{}) bool { switch x.(type) { case string: return true; default: return false } },
			},
			want: []interface{}{"a", "1"},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			var got []interface{} = interfaces.Filter(tt.args.s, tt.args.f)
			assert.Equal(t, tt.want, got)
			got = interfaces.New(tt.args.s).Filter(tt.args.f)
			assert.Equal(t, tt.want, got)
		})
	}
}

func TestReduce(t *testing.T) {
	type args struct {
		s       []interface{}
		f       func(sum, value interface{}) interface{}
		neutral interface{}
	}
	tests := []struct {
		name string
		args args
		want interface{}
	}{
		{
			name: "basic",
			args: args{
				s:       []interface{}{"a", 1, "1", 2},
				f:       func(sum, value interface{}) interface{} { return fmt.Sprint(sum) + fmt.Sprint(value) },
				neutral: "",
			},
			want: "a112",
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			var got interface{} = interfaces.Reduce(tt.args.s, tt.args.f, tt.args.neutral)
			assert.Equal(t, tt.want, got)
			got = interfaces.New(tt.args.s).Reduce(tt.args.f, tt.args.neutral)
			assert.Equal(t, tt.want, got)
		})
	}
}

func TestUnique(t *testing.T) {
	type args struct {
		s []interface{}
	}
	tests := []struct {
		name string
		args args
		want []interface{}
	}{
		{
			name: "basic",
			args: args{
				s: []interface{}{"a", 1, "1", 1, 2, "a"},
			},
			want: []interface{}{"a", 1, "1", 2},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			var got []interface{} = interfaces.Unique(tt.args.s)
			assert.Equal(t, tt.want, got)
			got = interfaces.New(tt.args.s).Unique()
			assert.Equal(t, tt.want, got)
		})
	}
}

func TestIntersect(t *testing.T) {
	type args struct {
		s    []interface{}
		more [][]interface{}
	}
	tests := []struct {
		name string
		args args
		want []interface{}
	}{
		{
			name: "same",
			args: args{
				s: []interface{}{"a", 1, "1", 1, 2, "a"},
				more: [][]interface{}{{"a", 1, "1", 1, 2, "a"}},
			},
			want: []interface{}{"a", 1, "1", 1, 2, "a"},
		},{
			name: "multiple",
			args: args{
				s: []interface{}{"a", 1, "1", 1, 2, "a"},
				more: [][]interface{}{{"a", 1, "1"}, {"1", 1}},
			},
			want: []interface{}{1, "1"},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			var got []interface{} = interfaces.Intersect(tt.args.s, tt.args.more...)
			assert.ElementsMatch(t, tt.want, got)
			got = interfaces.New(tt.args.s).Intersect(tt.args.more...)
			assert.ElementsMatch(t, tt.want, got)
		})
	}
}
