// Code generated by go generate; DO NOT EDIT.
// This file was generated at 2018 Aug 08 16:59:04 UTC

// Copyright 2018 Dennis Kuhnert
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Package interfaces provides ...
package interfaces

// interfaces ...
type interfaces []interface{}

// New ...
func New(s []interface{}) interfaces {
	return interfaces(s)
}

// Map ...
func Map(s []interface{}, f func(s interface{}) interface{}) interfaces {
	m := interfaces(make([]interface{}, len(s)))
	for i, v := range s {
		m[i] = f(v)
	}
	return m
}

// Map ...
func (s interfaces) Map(f func(s interface{}) interface{}) interfaces {
	return Map(s, f)
}

// Filter ...
func Filter(s []interface{}, f func(s interface{}) bool) interfaces {
	m := interfaces(make([]interface{}, 0, len(s)))
	for _, v := range s {
		if f(v) {
			m = append(m, v)
		}
	}
	return m
}

// Filter ...
func (s interfaces) Filter(f func(s interface{}) bool) interfaces {
	return Filter(s, f)
}

// Reduce ...
func Reduce(s []interface{}, f func(sum, value interface{}) interface{}, neutral interface{}) interface{} {
	res := neutral
	for _, e := range s {
		res = f(res, e)
	}
	return res
}

// Reduce ...
func (s interfaces) Reduce(f func(sum, value interface{}) interface{}, neutral interface{}) interface{} {
	return Reduce(s, f, neutral)
}

// Unique ...
func Unique(s []interface{}) interfaces {
	m := interfaces(make([]interface{}, 0, len(s)))
	seen := make(map[interface{}]struct{})
	for _, v := range s {
		if _, ok := seen[v]; !ok {
			m = append(m, v)
			seen[v] = struct{}{}
		}
	}
	return m
}

// Unique ...
func (s interfaces) Unique() interfaces {
	return Unique(s)
}
