// Code generated by go generate; DO NOT EDIT.
// This file was generated at 2018 Aug 08 16:59:04 UTC

// Copyright 2018 Dennis Kuhnert
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Package uints provides ...
package uints

// uints ...
type uints []uint

// New ...
func New(s []uint) uints {
	return uints(s)
}

// Map ...
func Map(s []uint, f func(s uint) uint) uints {
	m := uints(make([]uint, len(s)))
	for i, v := range s {
		m[i] = f(v)
	}
	return m
}

// Map ...
func (s uints) Map(f func(s uint) uint) uints {
	return Map(s, f)
}

// Filter ...
func Filter(s []uint, f func(s uint) bool) uints {
	m := uints(make([]uint, 0, len(s)))
	for _, v := range s {
		if f(v) {
			m = append(m, v)
		}
	}
	return m
}

// Filter ...
func (s uints) Filter(f func(s uint) bool) uints {
	return Filter(s, f)
}

// Reduce ...
func Reduce(s []uint, f func(sum, value uint) uint, neutral uint) uint {
	res := neutral
	for _, e := range s {
		res = f(res, e)
	}
	return res
}

// Reduce ...
func (s uints) Reduce(f func(sum, value uint) uint, neutral uint) uint {
	return Reduce(s, f, neutral)
}

// Unique ...
func Unique(s []uint) uints {
	m := uints(make([]uint, 0, len(s)))
	seen := make(map[uint]struct{})
	for _, v := range s {
		if _, ok := seen[v]; !ok {
			m = append(m, v)
			seen[v] = struct{}{}
		}
	}
	return m
}

// Unique ...
func (s uints) Unique() uints {
	return Unique(s)
}
